services:
  reviews:
    build: .
    image: ghcr.io/chanayus/bookinfo-reviews:dev
    ports:
      - "8082:9080"
    environment:
      ENABLE_RATINGS: 'true'
      RATINGS_SERVICE: http://ratings:8080/
